/* I Am From Hetauda — local-first personalization, no login */
(function(){
'use strict';
if(window.__IFH_PERSONALIZATION__)return;window.__IFH_PERSONALIZATION__=true;
var KEY='ifh_category_reads',SOURCE='ifh_source_reads',LOCAL='ifh_local_interest';
var $=function(s){return document.querySelector(s)};
function read(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch(e){return{}}}
function write(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch(e){}}
function add(key,name){if(!name)return;var a=read(key);a[name]=(Number(a[name])||0)+1;write(key,a)}
function local(n){var s=((n.title||'')+' '+(n.description||'')+' '+(n.source||'')+' '+(n.category||'')).toLowerCase();return n.local===true||/hetauda|हेटौंडा|हेटौँडा|मकवानपुर|makwanpur/.test(s)}
function date(n){var d=new Date(n&&(n.published||n.pubDate||n.date||''));return isNaN(d.getTime())?null:d}
function age(n){var d=date(n);return d?Math.max(0,(Date.now()-d.getTime())/3600000):999}
function saved(id){try{return JSON.parse(localStorage.getItem('saved_news')||'[]').indexOf(id)>=0}catch(e){return false}}
function profile(){return {cat:read(KEY),source:read(SOURCE),local:Number(localStorage.getItem(LOCAL)||0)}}
function track(n){if(!n)return;add(KEY,n.category||'nepal');add(SOURCE,n.source||'');if(local(n))localStorage.setItem(LOCAL,String(profile().local+1))}
function score(n,p){var s=Number(n.score||0);s+=Number(n.source_count||0)*4;s+=n.verified?8:0;s+=(n.image_local||n.image)?2:0;s+=local(n)?(p.local>1?34:24):0;s+=(Number(p.cat[n.category]||0)*7);s+=(Number(p.source[n.source]||0)*2);var h=age(n);if(h<1)s+=18;else if(h<6)s+=12;else if(h<24)s+=6;else if(h<48)s+=2;if(saved(n.id))s+=5;return s}
function unique(items){var seen={},out=[];items.forEach(function(n){var k=String(n.id||n.link||n.title);if(!seen[k]){seen[k]=1;out.push(n)}});return out}
function card(n){var im=n.image_local||n.image||'';return '<button class="ifhRecCard" data-rec-id="'+String(n.id||'').replace(/"/g,'&quot;')+'"><div class="ifhRecMedia">'+(im?'<img loading="lazy" src="'+String(im).replace(/"/g,'&quot;')+'" alt="">':'<span>📰</span>')+'</div><div class="ifhRecBody"><div class="ifhRecMeta">'+(local(n)?'📍 Hetauda • ':'')+String(n.source||'')+'</div><strong>'+String(n.title||'')+'</strong><small>'+((n.source_count>1)?'✓ '+n.source_count+' स्रोत • ':'')+(age(n)<1?'अहिले':age(n)<24?Math.floor(age(n))+' घण्टा अघि':Math.floor(age(n)/24)+' दिन अघि')+'</small></div></button>'}
function mount(){var news=$('#news');if(!news||$('#ifhPersonalSections'))return false;var host=document.createElement('div');host.id='ifhPersonalSections';host.innerHTML='<section class="ifhRecSection" id="ifhForYou"><div class="ifhRecHead"><div><span class="ifhRecKicker">PERSONALIZED</span><h2>तपाईंका लागि</h2><p>तपाईंले पढ्नुभएको समाचारको आधारमा छनोट</p></div></div><div class="ifhRecGrid" id="ifhForYouGrid"></div></section><section class="ifhRecSection" id="ifhLocal"><div class="ifhRecHead"><div><span class="ifhRecKicker">LOCAL FIRST</span><h2>हेटौंडा प्राथमिकता</h2><p>हेटौंडा र मकवानपुरका समाचार पहिले</p></div></div><div class="ifhRecGrid" id="ifhLocalGrid"></div></section><section class="ifhRecSection" id="ifhTrending"><div class="ifhRecHead"><div><span class="ifhRecKicker">LIVE SIGNAL</span><h2>अहिले चर्चामा</h2><p>बहु-स्रोत र नयाँ अपडेटका आधारमा</p></div></div><div class="ifhRecGrid" id="ifhTrendingGrid"></div></section>';
news.parentNode.insertBefore(host,news);return true}
function render(items){if(!mount())return false;var p=profile(),base=unique(items.slice());var personal=base.slice().sort(function(a,b){return score(b,p)-score(a,p)}).slice(0,6);var locals=base.filter(local).sort(function(a,b){return score(b,p)-score(a,p)}).slice(0,4);var trend=base.slice().sort(function(a,b){return (Number(b.source_count||0)*20+Number(b.score||0)+Math.max(0,24-age(b)*2))-(Number(a.source_count||0)*20+Number(a.score||0)+Math.max(0,24-age(a)*2))}).slice(0,4);
var hasHistory=Object.keys(p.cat).length||Object.keys(p.source).length||p.local>0;$('#ifhForYouGrid').innerHTML=personal.map(card).join('');$('#ifhForYou').style.display='block';$('#ifhForYou .ifhRecHead p').textContent=hasHistory?'तपाईंको पढ्ने रुचिअनुसार':'ताजा, स्थानीय र विश्वसनीय समाचारबाट सुरुवात';$('#ifhLocalGrid').innerHTML=locals.map(card).join('');$('#ifhLocal').style.display=locals.length?'block':'none';$('#ifhTrendingGrid').innerHTML=trend.map(card).join('');return true}
function css(){if($('#ifh-personal-style'))return;var s=document.createElement('style');s.id='ifh-personal-style';s.textContent='.ifhRecSection{margin:0 0 22px}.ifhRecHead{display:flex;justify-content:space-between;align-items:end;margin:0 2px 10px}.ifhRecKicker{font-size:9px;font-weight:900;letter-spacing:1px;color:#e11d48}.ifhRecHead h2{font-size:20px;line-height:1.2;margin:3px 0}.ifhRecHead p{font-size:10px;color:var(--muted);margin:0}.ifhRecGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.ifhRecCard{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:14px;padding:0;overflow:hidden;text-align:left;cursor:pointer;box-shadow:0 5px 18px rgba(16,24,40,.06);transition:.18s}.ifhRecCard:hover{transform:translateY(-2px);box-shadow:0 14px 30px rgba(16,24,40,.1)}.ifhRecMedia{height:112px;background:var(--soft);display:flex;align-items:center;justify-content:center;font-size:30px;overflow:hidden}.ifhRecMedia img{width:100%;height:100%;object-fit:cover}.ifhRecBody{padding:9px 10px 11px}.ifhRecMeta{font-size:8px;color:var(--muted);margin-bottom:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ifhRecBody strong{display:block;font-size:12px;line-height:1.45}.ifhRecBody small{display:block;color:var(--muted);font-size:8px;margin-top:6px}.uxDark .ifhRecCard{background:#101828;border-color:#253047}.uxDark .ifhRecBody strong{color:#f8fafc}@media(max-width:950px){.ifhRecGrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.ifhRecSection{margin-bottom:18px}.ifhRecGrid{display:flex;overflow:auto;gap:9px;padding-bottom:3px;scrollbar-width:none}.ifhRecGrid::-webkit-scrollbar{display:none}.ifhRecCard{min-width:230px}.ifhRecMedia{height:115px}.ifhRecHead h2{font-size:18px}}';document.head.appendChild(s)}
function reset(){localStorage.removeItem(KEY);localStorage.removeItem(SOURCE);localStorage.removeItem(LOCAL);refresh()}
function refresh(){if(!window.fetch)return;fetch('./data/news.json?personal='+Date.now(),{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){render(Array.isArray(d.items)?d.items:[])}).catch(function(){})}
function setup(){css();var tries=0;function wait(){if(mount()){refresh();return}if(++tries<30)setTimeout(wait,250)}wait();document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-id],[data-rec-id]');if(!b)return;var id=b.getAttribute('data-id')||b.getAttribute('data-rec-id');if(!id)return;var title=b.querySelector&&b.querySelector('.title,.ifhRecBody strong');setTimeout(function(){fetch('./data/news.json?personal-track='+Date.now(),{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){var n=(d.items||[]).find(function(x){return String(x.id)===String(id)});if(n)track(n)}).catch(function(){})},0)},true);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();window.IFHResetRecommendations=reset;window.IFHRefreshRecommendations=refresh;
})();
