/* I Am From Hetauda — News Feed 12.0 Read Mode */
(function(){
'use strict';
if(window.__IFH_READ_MODE__)return;window.__IFH_READ_MODE__=true;
var current=null,items=[],font=1,spacing=1.55;
var $=function(s){return document.querySelector(s)};
function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function age(n){var d=new Date(n&&n.published||'');return isNaN(d)?999999:Math.max(0,(Date.now()-d.getTime())/60000)}
function readTime(n){var t=String(n&&n.description||'')+' '+String(n&&n.title||'');return Math.max(1,Math.ceil(t.trim().split(/\s+/).length/55))}
function important(n){if(!n)return 'यस समाचारलाई धेरै स्रोतले रिपोर्ट गरेको छ वा यो पछिल्लो समयको महत्वपूर्ण अपडेट हुन सक्छ।';var bits=[];if(n.verified||Number(n.source_count||0)>1)bits.push('एकभन्दा बढी स्रोतमा रिपोर्ट भएको');if(n.local===true||/हेटौंडा|हेटौँडा|मकवानपुर|hetauda|makwanpur/i.test((n.title||'')+' '+(n.description||'')))bits.push('हेटौंडा/मकवानपुरसँग सम्बन्धित');if(age(n)<=60)bits.push('पछिल्लो १ घण्टाभित्र अपडेट भएको');if(n.image_local||n.image)bits.push('फोटोसहित आएको');return bits.length?'यो समाचार '+bits.join(' र ')+' भएकाले ध्यान दिन योग्य छ।':'यो समाचार अहिलेको समाचार प्रवाहमा उपयोगी अपडेटका रूपमा देखिएको छ।'}
function mount(){var body=$('.reader .modalbody');if(!body||$('#ifhReadTools'))return !!body;var tools=document.createElement('div');tools.id='ifhReadTools';tools.className='ifhReadTools';tools.innerHTML='<div class="ifhReadTop"><b>📖 READ MODE</b><span id="ifhReadTime"></span></div><div class="ifhReadBtns"><button data-font="-">A−</button><button data-font="+">A+</button><button data-space="-">↕ कम</button><button data-space="+">↕ बढी</button></div><div id="ifhWhy" class="ifhWhy"></div><div id="ifhRelated" class="ifhRelated"></div>';
body.insertBefore(tools,body.firstChild);
tools.querySelector('[data-font="-"]').onclick=function(){font=Math.max(.85,font-.08);apply()};tools.querySelector('[data-font="+"]').onclick=function(){font=Math.min(1.45,font+.08);apply()};tools.querySelector('[data-space="-"]').onclick=function(){spacing=Math.max(1.3,spacing-.1);apply()};tools.querySelector('[data-space="+"]').onclick=function(){spacing=Math.min(2,spacing+.1);apply()};return true}
function related(){var box=$('#ifhRelated');if(!box||!current)return;var cat=current.category,src=current.source;var a=items.filter(function(n){return n.id!==current.id&&(n.category===cat||n.source===src)}).sort(function(a,b){return age(a)-age(b)}).slice(0,4);box.innerHTML=a.length?'<strong>तपाईंलाई सम्बन्धित समाचार</strong>'+a.map(function(n){return '<button data-related="'+esc(n.id)+'"><span>'+(n.image_local||n.image?'🖼️':'📰')+'</span><b>'+esc(n.title)+'</b><small>'+esc(n.source||'')+' • '+Math.floor(age(n))+' मिनेट अघि</small></button>'}).join(''):'';box.querySelectorAll('[data-related]').forEach(function(b){b.onclick=function(){if(window.openById)window.openById(b.dataset.related)}})}
function apply(){var d=$('.reader .description');if(d){d.style.fontSize=(15*font)+'px';d.style.lineHeight=String(spacing)}try{localStorage.setItem('ifh_read_font',font);localStorage.setItem('ifh_read_spacing',spacing)}catch(e){}}
function show(n){current=n||null;if(!mount()||!current)return;$('#ifhReadTime').textContent='⏱ '+readTime(current)+' मिनेट पढाइ';$('#ifhWhy').innerHTML='<strong>💡 यो समाचार किन महत्वपूर्ण?</strong><p>'+esc(important(current))+'</p>';apply();related()}
function patch(){if(!window.openById||window.__IFH_READ_PATCHED__)return false;var old=window.openById;window.openById=function(id){var r=old.apply(this,arguments);setTimeout(function(){var n=items.find(function(x){return String(x.id)===String(id)});show(n)},30);return r};window.__IFH_READ_PATCHED__=true;return true}
function load(){fetch('./data/news.json?readmode='+Date.now(),{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){items=Array.isArray(d.items)?d.items:[];if(current)related()}).catch(function(){})}
function css(){if($('#ifh-read12-style'))return;var s=document.createElement('style');s.id='ifh-read12-style';s.textContent='.ifhReadTools{margin:0 0 16px;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--soft)}.ifhReadTop{display:flex;justify-content:space-between;font-size:10px;margin-bottom:9px}.ifhReadTop span{color:var(--muted)}.ifhReadBtns{display:flex;gap:6px;flex-wrap:wrap}.ifhReadBtns button{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:9px;padding:7px 10px;font-weight:800;font-size:10px}.ifhWhy{margin-top:11px;padding:10px;border-radius:11px;background:var(--card);font-size:11px;line-height:1.55}.ifhWhy p{margin:4px 0 0;color:var(--muted)}.ifhRelated{margin-top:12px}.ifhRelated>strong{display:block;font-size:11px;margin-bottom:7px}.ifhRelated button{width:100%;display:grid;grid-template-columns:24px 1fr;gap:2px 7px;text-align:left;border:0;border-top:1px solid var(--line);padding:8px 0;background:transparent;color:var(--ink)}.ifhRelated b{font-size:10px;line-height:1.35}.ifhRelated small{grid-column:2;color:var(--muted);font-size:8px}.uxDark .ifhReadTools{background:#111827}.uxDark .ifhReadBtns button{background:#0b1220;color:#fff;border-color:#273449}@media(max-width:600px){.ifhReadBtns button{flex:1;min-width:60px}.ifhReadTools{border-radius:12px}}';document.head.appendChild(s)}
function start(){css();try{font=parseFloat(localStorage.getItem('ifh_read_font')||'1');spacing=parseFloat(localStorage.getItem('ifh_read_spacing')||'1.55')}catch(e){}load();if(!patch())setTimeout(start,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
