/* I Am From Hetauda — Read Later + Reading History + Continue Reading */
(function(){
'use strict';
if(window.__IFH_READING_HISTORY__)return;window.__IFH_READING_HISTORY__=true;
var HISTORY='ifh_read_history',LATER='ifh_read_later',PROGRESS='ifh_read_progress';
function get(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}}
function put(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function now(){return Date.now()}
function history(){return get(HISTORY,[])}
function later(){return get(LATER,[])}
function progress(){return get(PROGRESS,{})}
function remember(id){if(!id)return;var a=history().filter(function(x){return x!==id});a.unshift(id);put(HISTORY,a.slice(0,200))}
function toggleLater(id){if(!id)return;var a=later(),i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.unshift(id);put(LATER,a.slice(0,200));render()}
function setProgress(id,p){if(!id)return;var a=progress();a[id]={p:Math.max(0,Math.min(100,Number(p)||0)),at:now()};put(PROGRESS,a)}
function removeProgress(id){var a=progress();delete a[id];put(PROGRESS,a)}
function data(){return fetch('./data/news.json?reading='+Date.now(),{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){return Array.isArray(d.items)?d.items:[]})}
function find(items,id){return items.find(function(n){return String(n.id)===String(id)})}
function age(n){var d=new Date(n&&(n.published||''));if(isNaN(d.getTime()))return '';var m=Math.max(0,(Date.now()-d.getTime())/60000);return m<60?Math.floor(m)+' मिनेट अघि':m<1440?Math.floor(m/60)+' घण्टा अघि':Math.floor(m/1440)+' दिन अघि'}
function card(n,type){var p=progress()[n.id],pct=p&&p.p?Math.round(p.p):0,im=n.image_local||n.image||'';return '<button class="ifhReadCard" data-read-id="'+String(n.id).replace(/"/g,'&quot;')+'"><div class="ifhReadMedia">'+(im?'<img loading="lazy" src="'+String(im).replace(/"/g,'&quot;')+'" alt="">':'<span>📰</span>')+(pct>0&&pct<95?'<i style="width:'+pct+'%"></i>':'')+'</div><div class="ifhReadBody"><div class="ifhReadMeta">'+(type==='later'?'🔖 पढ्न बाँकी':'🕘 इतिहास')+' • '+age(n)+'</div><strong>'+String(n.title||'')+'</strong><small>'+String(n.source||'')+(pct>0&&pct<95?' • '+pct+'% पढिएको':'')+'</small></div></button>'}
function mount(){if(document.getElementById('ifhReadingSections'))return true;var news=document.querySelector('#news');if(!news||!news.parentNode)return false;var host=document.createElement('div');host.id='ifhReadingSections';host.innerHTML='<section class="ifhReadSection" id="ifhContinue"><div class="ifhReadHead"><div><span class="ifhReadKicker">CONTINUE READING</span><h2>जारी राख्नुहोस्</h2><p>तपाईंले अधुरो छोडेका समाचार</p></div></div><div class="ifhReadGrid" id="ifhContinueGrid"></div></section><section class="ifhReadSection" id="ifhLater"><div class="ifhReadHead"><div><span class="ifhReadKicker">READ LATER</span><h2>पछि पढ्नुहोस्</h2><p>सेभ गरेर राखिएका पढ्न बाँकी समाचार</p></div></div><div class="ifhReadGrid" id="ifhLaterGrid"></div></section><section class="ifhReadSection" id="ifhHistory"><div class="ifhReadHead"><div><span class="ifhReadKicker">RECENTLY READ</span><h2>हालै पढिएका</h2><p>तपाईंले खोलेका पछिल्ला समाचार</p></div><button class="ifhClearRead" id="ifhClearHistory">इतिहास खाली</button></div><div class="ifhReadGrid" id="ifhHistoryGrid"></div></section>';news.parentNode.insertBefore(host,news);document.getElementById('ifhClearHistory').onclick=function(){if(confirm('पढाइ इतिहास खाली गर्ने?')){put(HISTORY,[]);put(PROGRESS,{});render()}};return true}
function render(){if(!mount())return;data().then(function(items){var p=progress(),h=history(),l=later(),continueIds=Object.keys(p).filter(function(id){return p[id]&&p[id].p>0&&p[id].p<95}).sort(function(a,b){return (p[b].at||0)-(p[a].at||0)}).slice(0,4),laterItems=l.map(function(id){return find(items,id)}).filter(Boolean).slice(0,6),histItems=h.map(function(id){return find(items,id)}).filter(Boolean).slice(0,6),cont=continueIds.map(function(id){return find(items,id)}).filter(Boolean);document.getElementById('ifhContinueGrid').innerHTML=cont.map(function(n){return card(n,'continue')}).join('');document.getElementById('ifhLaterGrid').innerHTML=laterItems.map(function(n){return card(n,'later')}).join('');document.getElementById('ifhHistoryGrid').innerHTML=histItems.map(function(n){return card(n,'history')}).join('');document.getElementById('ifhContinue').style.display=cont.length?'block':'none';document.getElementById('ifhLater').style.display=laterItems.length?'block':'none';document.getElementById('ifhHistory').style.display=histItems.length?'block':'none';document.querySelectorAll('[data-read-id]').forEach(function(b){b.onclick=function(){var id=b.dataset.readId;var n=find(items,id);if(n){remember(id);if(window.openById)window.openById(id);else if(window.IFHOpenById)window.IFHOpenById(id)}}})}).catch(function(){})}
function injectStyle(){if(document.getElementById('ifh-reading-style'))return;var s=document.createElement('style');s.id='ifh-reading-style';s.textContent='.ifhReadSection{margin:0 0 22px}.ifhReadHead{display:flex;align-items:end;justify-content:space-between;margin:0 2px 10px}.ifhReadKicker{font-size:9px;font-weight:900;letter-spacing:1px;color:#667085}.ifhReadHead h2{font-size:19px;margin:3px 0}.ifhReadHead p{font-size:10px;color:var(--muted);margin:0}.ifhClearRead{border:1px solid var(--line);background:var(--card);color:var(--muted);border-radius:9px;padding:7px 9px;font-size:9px;font-weight:800}.ifhReadGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.ifhReadCard{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:14px;padding:0;overflow:hidden;text-align:left;cursor:pointer;position:relative}.ifhReadMedia{height:105px;background:var(--soft);position:relative;display:flex;align-items:center;justify-content:center;font-size:28px;overflow:hidden}.ifhReadMedia img{width:100%;height:100%;object-fit:cover}.ifhReadMedia i{position:absolute;left:0;bottom:0;height:3px;background:var(--accent);display:block}.ifhReadBody{padding:9px}.ifhReadMeta{font-size:8px;color:var(--muted);margin-bottom:4px}.ifhReadBody strong{display:block;font-size:12px;line-height:1.45}.ifhReadBody small{display:block;font-size:8px;color:var(--muted);margin-top:5px}@media(max-width:950px){.ifhReadGrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.ifhReadGrid{display:flex;overflow:auto;gap:9px;scrollbar-width:none}.ifhReadGrid::-webkit-scrollbar{display:none}.ifhReadCard{min-width:225px}.ifhReadMedia{height:112px}}.uxDark .ifhReadCard{background:#101828;border-color:#253047}.uxDark .ifhReadBody strong{color:#f8fafc}';document.head.appendChild(s)}
function setup(){injectStyle();var tries=0;function wait(){if(mount()){render();return}if(++tries<30)setTimeout(wait,250)}wait();document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('#news .card,[data-read-id]');if(!b)return;var id=b.getAttribute('data-id')||b.getAttribute('data-read-id');if(id)remember(id)},true)}
window.IFHToggleReadLater=toggleLater;window.IFHSetReadProgress=setProgress;window.IFHReadingRefresh=render;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();})();
