/* I Am From Hetauda — resilient runtime + news intelligence layer */
(function(){
'use strict';
if(window.__IFH_RUNTIME_FIX__)return;window.__IFH_RUNTIME_FIX__=true;
var all=[],active='all',filterMode='all',searchTerm='';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function img(n){return n&&(n.image_local||n.image)||''}
function date(n){var d=new Date(n&&(n.published||n.pubDate||n.date||''));return isNaN(d.getTime())?null:d}
function ago(x){var d=date({published:x});if(!d)return '';var m=Math.max(0,(Date.now()-d.getTime())/60000);if(m<1)return 'अहिले';if(m<60)return Math.floor(m)+' मिनेट अघि';if(m<1440)return Math.floor(m/60)+' घण्टा अघि';return Math.floor(m/1440)+' दिन अघि'}
function saved(){try{return JSON.parse(localStorage.getItem('saved_news')||'[]')}catch(e){return[]}}
function isSaved(id){return !!id&&saved().indexOf(id)>=0}
function toggleSave(id){var a=saved(),i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.unshift(id);localStorage.setItem('saved_news',JSON.stringify(a.slice(0,300)));render()}
function local(n){var s=((n.title||'')+' '+(n.description||'')+' '+(n.source||'')+' '+(n.category||'')).toLowerCase();return n.local===true||/hetauda|हेटौंडा|हेटौँडा|मकवानपुर|makwanpur/.test(s)}
function verified(n){return n.verified===true||Number(n.source_count||0)>1}
function sameDay(d){if(!d)return false;var x=new Date();return d.getFullYear()===x.getFullYear()&&d.getMonth()===x.getMonth()&&d.getDate()===x.getDate()}
function storyGroups(items){if(window.IFHStoryGroups)return window.IFHStoryGroups(items);return items.map(function(n){return n})}
function filtered(){var a=active==='saved'?all.filter(function(n){return isSaved(n.id)}):(active==='all'?all:all.filter(function(n){return n.category===active}));var now=Date.now();if(filterMode==='today')a=a.filter(function(n){return sameDay(date(n))});if(filterMode==='hour')a=a.filter(function(n){var d=date(n);return d&&now-d.getTime()<=3600000&&now-d.getTime()>=-300000});if(filterMode==='photo')a=a.filter(function(n){return !!img(n)});if(filterMode==='verified')a=a.filter(verified);if(filterMode==='local')a=a.filter(local);if(searchTerm){var q=searchTerm.toLowerCase();a=a.filter(function(n){return ((n.title||'')+' '+(n.description||'')+' '+(n.source||'')).toLowerCase().indexOf(q)>=0})}return storyGroups(a)}
function ensureFilters(){var status=$('.status');if(!status||$('.filterRow'))return;var row=document.createElement('div');row.className='filterRow';row.innerHTML=[['all','सबै'],['today','आज'],['hour','१ घण्टा'],['photo','📷 फोटो'],['verified','✓ verified'],['local','📍 हेटौंडा'],['saved','★ सेभ']].map(function(x){return '<button class="filterChip" data-filter="'+x[0]+'">'+x[1]+'</button>'}).join('');status.parentNode.insertBefore(row,status);$$('.filterChip').forEach(function(b){b.onclick=function(){filterMode=b.dataset.filter;if(filterMode==='saved')active='saved';else if(active==='saved')active='all';$$('.filterChip').forEach(function(x){x.classList.toggle('active',x===b)});render()}});$('.filterChip[data-filter="all"]').classList.add('active')}
function badge(n){var bits=[];var info=window.IFHStoryInfo?window.IFHStoryInfo(n):{count:1,sources:[n.source]};if(verified(n)||info.sources.length>1)bits.push('<span class="verified">✓ '+esc(info.sources.length||n.source_count||2)+' स्रोत</span>');if(info.count>1)bits.push('<span class="storyBadge">📰 '+info.count+' रिपोर्ट</span>');if(local(n))bits.push('<span class="localBadge">📍 Hetauda</span>');if(img(n))bits.push('<span class="photoBadge">📷</span>');return bits.join('')}
function sourceLine(n){var info=window.IFHStoryInfo?window.IFHStoryInfo(n):{sources:n.related_sources||[n.source]};return (info.sources||[]).slice(0,6).map(esc).join(' • ')}
function render(){ensureFilters();var box=$('#news'),a=filtered();if(!box)return;if(!a.length){box.innerHTML='<div class="empty"><div style="font-size:38px">🔎</div><h3>समाचार भेटिएन</h3><p>फिल्टर हटाएर वा अर्को शब्द खोजेर हेर्नुहोस्।</p><button class="filterChip" onclick="window.IFHclearFilters()">सबै समाचार देखाउनुहोस्</button></div>';return}var top=a.slice(0,5),bt=$('#breakingTrack');if(bt)bt.innerHTML=top.map(function(n){return '<span data-open="'+esc(n.id)+'">'+esc(n.title)+'</span>'}).join('<i>•</i>');box.innerHTML=a.map(function(n,i){var im=img(n),info=window.IFHStoryInfo?window.IFHStoryInfo(n):{count:1,sources:[n.source]};return '<article class="card '+(i===0?'featured':'')+'" data-id="'+esc(n.id)+'"><div class="intelBadges">'+badge(n)+'</div>'+(im?'<img class="thumb" loading="lazy" src="'+esc(im)+'" onerror="this.style.display=\'none\'" alt="">':'')+'<div class="cardbody"><div class="meta"><span><span class="source">'+esc(n.source||'')+'</span></span><span>'+ago(n.published)+'</span></div><h2 class="title">'+esc(n.title)+'</h2>'+(info.sources&&info.sources.length>1?'<div class="sourceCompare">स्रोत: '+sourceLine(n)+'</div>':'')+'<div class="tap">'+(isSaved(n.id)?'★ सेभ गरिएको':'ट्याप गरेर पढ्नुहोस् →')+'</div><div class="cardActions"><button data-read="'+esc(n.id)+'">पढ्नुहोस्</button><button data-save="'+esc(n.id)+'">'+(isSaved(n.id)?'♥':'♡')+' सेभ</button><button data-share="'+esc(n.id)+'">↗</button></div></div></article>'}).join('');$$('#news .card').forEach(function(c){c.onclick=function(){openById(c.dataset.id)}});$$('#news [data-read]').forEach(function(b){b.onclick=function(e){e.stopPropagation();openById(b.dataset.read)}});$$('#news [data-save]').forEach(function(b){b.onclick=function(e){e.stopPropagation();toggleSave(b.dataset.save)}});$$('#news [data-share]').forEach(function(b){b.onclick=function(e){e.stopPropagation();shareById(b.dataset.share)}});$$('#breakingTrack [data-open]').forEach(function(b){b.onclick=function(){openById(b.dataset.open)}});var h=$('#heading');if(h)h.textContent=filterMode==='local'?'हेटौंडाका समाचार':filterMode==='today'?'आजका समाचार':filterMode==='hour'?'पछिल्लो १ घण्टा':filterMode==='verified'?'बहु-स्रोत verified समाचार':filterMode==='photo'?'फोटो भएका समाचार':active==='saved'?'सेभ गरिएका समाचार':active==='all'?'ताजा समाचार':'समाचार';var u=$('#updated');if(u&&all.length)u.textContent=a.length+' समाचार • '+all.length+' कुल'}
function openById(id){var n=all.find(function(x){return x.id===id});if(!n)return;try{var r=JSON.parse(localStorage.getItem('read_news')||'[]').filter(function(x){return x!==id});r.unshift(id);localStorage.setItem('read_news',JSON.stringify(r.slice(0,500)))}catch(e){}var modal=$('#modal');if(!modal)return;var im=$('#mi');im.style.display=img(n)?'block':'none';im.src=img(n)||'';im.alt=n.title||'';var info=window.IFHStoryInfo?window.IFHStoryInfo(n):{count:1,sources:[n.source]};$('#mm').textContent=(n.source||'')+' • '+ago(n.published)+(info.sources.length>1?' • '+info.sources.length+' स्रोत':'');$('#mt').textContent=n.title||'';$('#md').innerHTML=esc(n.description||'यस समाचारको थप विवरणका लागि मूल समाचार साइट खोल्नुहोस्।')+(info.sources.length>1?'<div class="sourcePanel"><strong>यो समाचार अन्य स्रोतमा पनि प्रकाशित:</strong><div>'+sourceLine(n)+'</div></div>':'');$('#ml').dataset.link=n.link||'';var sb=$('#saveBtn');if(sb){sb.textContent=isSaved(id)?'♥':'♡';sb.onclick=function(){toggleSave(id);sb.textContent=isSaved(id)?'♥':'♡'}}modal.classList.add('open');document.body.style.overflow='hidden'}
function closeReader(){var m=$('#modal');if(m)m.classList.remove('open');document.body.style.overflow=''}
function shareById(id){var n=all.find(function(x){return x.id===id});if(!n)return;var u=location.origin+location.pathname+'?news='+encodeURIComponent(id);if(navigator.share)navigator.share({title:n.title,text:n.title,url:u}).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText(u).then(function(){alert('लिंक copy भयो।')})}
function loadNews(){var box=$('#news');if(box)box.innerHTML=Array.from({length:6},function(){return '<div class="skeleton"></div>'}).join('');return fetch('./data/news.json?ts='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('news '+r.status);return r.json()}).then(function(d){all=Array.isArray(d.items)?d.items:[];if(!all.length)throw Error('empty news');var u=$('#updated');if(u)u.textContent='अन्तिम अपडेट: '+(d.updated_at?new Date(d.updated_at).toLocaleString('ne-NP'):'अहिले');var f=$('#sources');if(f)f.textContent='स्रोतहरू: '+(d.sources||[]).join(' • ');render();handleDeepLink()}).catch(function(e){console.error('IFH news load failed',e);if(box)box.innerHTML='<div class="empty"><div style="font-size:40px">⚠️</div><h3>समाचार डेटा लोड भएन</h3><p>इन्टरनेट जडान वा news.json जाँच गर्नुहोस्।</p><button class="filterChip" onclick="window.IFHloadNews()">फेरि प्रयास गर्नुहोस्</button></div>';var u=$('#updated');if(u)u.textContent='डेटा लोड समस्या'})}
function handleDeepLink(){var id=new URLSearchParams(location.search).get('news');if(id)openById(id)}
function setupSearch(){var s=$('#newsSearch');if(!s)return;s.addEventListener('input',function(){searchTerm=s.value.trim();render()})}
window.IFHclearFilters=function(){active='all';filterMode='all';searchTerm='';var s=$('#newsSearch');if(s)s.value='';$$('.filterChip').forEach(function(x){x.classList.toggle('active',x.dataset.filter==='all')});render()};window.IFHloadNews=loadNews;
if(!document.getElementById('ifh-intel-style')){var st=document.createElement('style');st.id='ifh-intel-style';st.textContent='.intelBadges{position:absolute;z-index:2;display:flex;gap:4px;flex-wrap:wrap;padding:8px}.card{position:relative}.localBadge,.photoBadge,.storyBadge{background:#eff6ff;color:#1d4ed8;padding:2px 6px;border-radius:99px;font-size:9px;font-weight:800}.photoBadge{background:#f5f3ff;color:#6d28d9}.storyBadge{background:#fff7ed;color:#c2410c}.sourceCompare{font-size:9px;color:#667085;margin-top:7px;line-height:1.5}.sourcePanel{margin-top:18px;padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--soft);font-size:12px;line-height:1.7}.cardActions{display:flex;gap:6px;margin-top:10px}.cardActions button{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:9px;padding:7px 9px;font-size:10px;font-weight:800;cursor:pointer}.cardActions button:first-child{margin-left:auto}.uxDark .cardActions button{background:#111827;color:#f8fafc;border-color:#253047}';document.head.appendChild(st)}
if($('#modal'))$('#modal').addEventListener('click',function(e){if(e.target===this)closeReader()});document.addEventListener('keydown',function(e){if(e.key==='Escape')closeReader()});setupSearch();ensureFilters();loadNews();setInterval(function(){if(document.visibilityState==='visible'&&navigator.onLine)loadNews()},300000);
})();
