const DB_NAME="iamfromhetauda-notifications",DB_VERSION=1,STORE="items",CACHE="iamfromhetauda-v17";
const SHELL=["./","./manifest.webmanifest","./logo.jpg","./data/news.json","./data/push-config.json","./story-intelligence.js","./personalization.js","./runtime-fix.js","./reading-history.js","./reader-v4.js","./live-feed.js","./smart-ranking.js","./breaking-mode.js","./news-radar.js","./news-dashboard.js","./story-timeline.js","./instant-search.js","./news-reels.js","./read-mode.js","./vertical-news-reels.js"];
const MAX_NOTIFICATIONS=150;
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL).catch(()=>{})).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>dbOpen()).then(db=>new Promise(resolve=>{const tx=db.transaction(STORE,"readwrite"),s=tx.objectStore(STORE),r=s.openCursor(),keys=[];r.onsuccess=()=>{const cur=r.result;if(!cur){while(keys.length>MAX_NOTIFICATIONS){s.delete(keys.shift())}resolve();return}keys.push({key:cur.key,created:cur.value.created||0});keys.sort((a,b)=>a.created-b.created);if(keys.length>MAX_NOTIFICATIONS)keys.splice(0,keys.length-MAX_NOTIFICATIONS);r.continue()};r.onerror=()=>resolve()})).then(()=>self.clients.claim())));
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"key"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function saveRecord(n){const item={key:String(n.id||n.tag||n.body||Date.now()),id:n.id||"",title:n.title||"I Am From Hetauda",body:n.body||"",image:n.image||"./logo.jpg",url:n.url||("./?news="+encodeURIComponent(n.id||"")),created:Date.now(),read:false};return dbOpen().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(item);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}))}
function markRead(key){if(!key)return Promise.resolve();return dbOpen().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite"),s=tx.objectStore(STORE),g=s.get(key);g.onsuccess=()=>{if(g.result){g.result.read=true;s.put(g.result)}};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}))}
self.addEventListener("push",e=>{let d={title:"I Am From Hetauda",body:"नयाँ समाचार उपलब्ध छ।",url:"./",image:"./logo.jpg",id:""};try{d=Object.assign(d,e.data?e.data.json():{})}catch(_){}const id=String(d.id||"");const notification={title:String(d.title||"I Am From Hetauda"),body:String(d.body||"नयाँ समाचार उपलब्ध छ।"),url:String(d.url||"./"),image:String(d.image||"./logo.jpg"),id,tag:id||"news"};e.waitUntil(Promise.all([saveRecord(notification),self.registration.showNotification(notification.title,{body:notification.body,icon:"./logo.jpg",image:notification.image,badge:"./logo.jpg",tag:notification.tag,renotify:true,data:{url:notification.url,id:id}})]).then(()=>self.clients.matchAll({type:"window",includeUncontrolled:true}).then(cs=>Promise.all(cs.map(c=>c.postMessage({type:"NEWS_NOTIFICATION",notification:notification}))))))});
self.addEventListener("notificationclick",e=>{e.notification.close();const data=e.notification.data||{},key=String(data.id||e.notification.tag||e.notification.body||"");const url=new URL(data.url||"./",self.location.origin).href;e.waitUntil(markRead(key).catch(()=>{}).then(()=>clients.matchAll({type:"window",includeUncontrolled:true})).then(cs=>{for(const c of cs){if("focus" in c){c.navigate(url);return c.focus()}}return clients.openWindow(url)}))});
self.addEventListener("notificationclose",e=>{const data=e.notification.data||{};if(data.id)markRead(String(data.id)).catch(()=>{})});
function isSiteHtml(u){return /\/iamfromhetauda\/?$/.test(u.pathname)||/\/iamfromhetauda\/index\.html$/.test(u.pathname)}
function injectRuntime(r){if(!r||!r.ok)return r;return r.text().then(t=>t.replace(/<\/body>/i,'<script src="./story-intelligence.js?v=17" defer></script><script src="./personalization.js?v=17" defer></script><script src="./reading-history.js?v=17" defer></script><script src="./reader-v4.js?v=17" defer></script><script src="./live-feed.js?v=17" defer></script><script src="./smart-ranking.js?v=17" defer></script><script src="./breaking-mode.js?v=17" defer></script><script src="./news-radar.js?v=17" defer></script><script src="./news-dashboard.js?v=17" defer></script><script src="./story-timeline.js?v=17" defer></script><script src="./instant-search.js?v=17" defer></script><script src="./news-reels.js?v=17" defer></script><script src="./read-mode.js?v=17" defer></script><script src="./runtime-fix.js?v=17" defer></script></body>')).then(t=>new Response(t,{status:r.status,statusText:r.statusText,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-cache"}}))}
self.addEventListener("fetch",e=>{const u=new URL(e.request.url);if(e.request.method!=="GET"||u.origin!==self.location.origin)return;if(u.pathname.endsWith("/data/news.json")){e.respondWith(fetch(e.request).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put(e.request,c));return r}).catch(()=>caches.match(e.request)));return}if(isSiteHtml(u)){e.respondWith(fetch(e.request).then(r=>injectRuntime(r).then(x=>{const c=x.clone();caches.open(CACHE).then(k=>k.put(e.request,c));return x})).catch(()=>caches.match(e.request).then(r=>r||caches.match("./index.html"))));return}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r.ok){const c=r.clone();caches.open(CACHE).then(x=>x.put(e.request,c))}return r}).catch(()=>caches.match("./index.html"))))});
